apiVersion: v1
kind: Service
metadata:
  name: wolfword
  namespace: aco-wolf
  labels:
    app: wolfword
spec:
  type: NodePort
  selector:
    app: wolfword
  ports:
    - name: http
      port: 80
      targetPort: http
